HW 4 Complete
MrRamka/otus pull request #4
Opened 2024-03-25 10:27 UTC by MrRamka

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-03-31 08:42 UTC, ityulkanov requested changes
Не нахожу правок в go.mod и необходимо чуть поправить интерфейс (т.к. по условиям дз их нельзя менять). в остальном отличная работа

2024-03-31 08:42 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +	isEmpty() bool
Я бы не рекомендовал расширять или каким то другим образом менять заданные в ДЗ интерфейсы ни сейчас ни в будущем, обычно ДЗ подразумевает что вы можете решить задачу с теми методами и интерфейсами что были в нём заданы

2024-05-06 17:19 UTC, MrRamka commented on hw04_lru_cache/list.go
> +	isEmpty() bool
Готово

2024-05-07 20:53 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		item = l.queue.Back()
не вижу тут логики удаления из items при переполнении, нужно дополнить.

2024-05-10 19:16 UTC, MrRamka commented on hw04_lru_cache/cache.go
> +		item = l.queue.Back()
А можете подсказать что еще требуется. Вроде как из массива все удалется. Если у нас переполнение, то происходит вызов функции [remove](https://github.com/MrRamka/otus/pull/4/files#diff-14de8bde71ab5ff8dc7d1eb68edcebede30a2d6d10081381165b8eb815f670b3R54) в которой уже происходит удаление из массива. 

Также [этот](https://github.com/MrRamka/otus/pull/4/files#diff-e3ba3d3b77badb2bc8726986770076e84ae97698efb9ca7e1ced484f73d4fe67R52) тест проверяет работу удаления

2024-05-16 13:35 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		item = l.queue.Back()
Да, точно, извиняюсь. Отвык в го уже от однострочных функций. Принял.

2024-05-16 13:35 UTC, ityulkanov approved these changes

2024-05-16 13:37 UTC, merged